version: "3.8"

services:
  api-manager-web:
    container_name: api-manager-web
    build:
      context: ..
      dockerfile: development/Dockerfile.dev
    network_mode: host
    volumes:
      - ..:/app
      - ../logs:/app/logs
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-apimanager}:${POSTGRES_PASSWORD:-CHANGE_THIS_PASSWORD}@127.0.0.1:5434/${POSTGRES_DB:-apimanager}
      - API_HOST=http://127.0.0.1:8080
      - CALLBACK_BASE_URL=http://127.0.0.1:8000
      - ALLOW_DIRECT_LOGIN=True
    env_file:
      - .env
    depends_on:
      - api-manager-db
    restart: unless-stopped

  api-manager-db:
    container_name: api-manager-db
    image: postgres:13
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-apimanager}
      - POSTGRES_USER=${POSTGRES_USER:-apimanager}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-CHANGE_THIS_PASSWORD}
    volumes:
      - api_manager_postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    restart: unless-stopped

volumes:
  api_manager_postgres_data:
