{
  "id":"atme0352a-9a0f-4bfa-b30b-9003aa467f51",
  "bank_id":"gh.29.uk",
  "name":"Atm by the Lake",
  "address":{
    "line_1":"No 1 the Road",
    "line_2":"The Place",
    "line_3":"The Hill",
    "city":"Berlin",
    "county":"",
    "state":"Brandenburg",
    "postcode":"13359",
    "country_code":"DE"
  },
  "location":{
    "latitude":11.45,
    "longitude":11.45
  },
  "meta":{
    "license":{
      "id":"ODbL-1.0",
      "name":"Open Database License"
    }
  },
  "monday":{
    "opening_time":"10:00",
    "closing_time":"18:00"
  },
  "tuesday":{
    "opening_time":"10:00",
    "closing_time":"18:00"
  },
  "wednesday":{
    "opening_time":"10:00",
    "closing_time":"18:00"
  },
  "thursday":{
    "opening_time":"10:00",
    "closing_time":"18:00"
  },
  "friday":{
    "opening_time":"10:00",
    "closing_time":"18:00"
  },
  "saturday":{
    "opening_time":"10:00",
    "closing_time":"18:00"
  },
  "sunday":{
    "opening_time":"10:00",
    "closing_time":"18:00"
  },
  "is_accessible":"true",
  "located_at":"no-example-provided",
  "more_info":"no-example-provided",
  "has_deposit_capability":"true",
  "supported_languages":["es","fr","de"],
  "services":["ATBP","ATBA"],
  "accessibility_features":["ATAC","ATAD"],
  "supported_currencies":["EUR","MXN","USD"],
  "notes":["String1","String2"],
  "location_categories":["ATBI","ATBE"],
  "minimum_withdrawal":"5",
  "branch_identification":"no-example-provided",
  "site_identification":"no-example-provided",
  "site_name":"no-example-provided",
  "cash_withdrawal_national_fee":"no-example-provided",
  "cash_withdrawal_international_fee":"no-example-provided",
  "balance_inquiry_fee":"no-example-provided"
}